/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_emulatorhandle_free: (a: number, b: number) => void;
export const emulatorhandle_auto_video_region: (a: number) => void;
export const emulatorhandle_build_version: () => [number, number];
export const emulatorhandle_debug_cram_colors_json: (a: number) => [number, number, number];
export const emulatorhandle_debug_render_plane: (a: number, b: number, c: number) => [number, number, number];
export const emulatorhandle_debug_render_tiles: (a: number, b: number) => [number, number, number];
export const emulatorhandle_debug_sprites_json: (a: number) => [number, number, number];
export const emulatorhandle_get_cpu_state: (a: number) => [number, number, number];
export const emulatorhandle_get_cram: (a: number) => [number, number];
export const emulatorhandle_get_framebuffer_argb: (a: number) => [number, number];
export const emulatorhandle_get_memory: (a: number, b: number, c: number) => [number, number];
export const emulatorhandle_get_sram: (a: number) => [number, number];
export const emulatorhandle_get_sram_info: (a: number) => [number, number, number];
export const emulatorhandle_get_vdp_registers_json: (a: number) => [number, number, number];
export const emulatorhandle_get_video_region: (a: number) => [number, number];
export const emulatorhandle_get_vram: (a: number) => [number, number];
export const emulatorhandle_has_sram: (a: number) => number;
export const emulatorhandle_is_video_region_auto: (a: number) => number;
export const emulatorhandle_load_rom: (a: number, b: number, c: number) => [number, number];
export const emulatorhandle_load_sram: (a: number, b: number, c: number) => void;
export const emulatorhandle_load_state: (a: number, b: number, c: number) => [number, number];
export const emulatorhandle_new: () => number;
export const emulatorhandle_pause: (a: number) => void;
export const emulatorhandle_reset: (a: number) => void;
export const emulatorhandle_resume: (a: number) => void;
export const emulatorhandle_run_frame: (a: number) => void;
export const emulatorhandle_save_state: (a: number) => [number, number, number, number];
export const emulatorhandle_set_breakpoint: (a: number, b: number) => void;
export const emulatorhandle_set_controller_state: (a: number, b: number, c: number) => void;
export const emulatorhandle_set_video_region: (a: number, b: number, c: number) => [number, number];
export const emulatorhandle_step: (a: number, b: number) => void;
export const emulatorhandle_step_instruction: (a: number) => void;
export const emulatorhandle_take_audio_samples: (a: number, b: number) => [number, number];
export const emulatorhandle_trace_execution: (a: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
