'use strict';

const fs = require('fs');
const path = require('path');
const manifest = require('./manifest.json');
const stgService = require('../horizontal-stg-editor/horizontal-stg-service');

const ENGINE_SOURCE_FILES = [
  'bullet/enemy_bullet.c',
  'bullet/player_bullet.c',
  'collision/collision.c',
  'effect/effect.c',
  'enemy/boss.c',
  'enemy/enemy.c',
  'game/game.c',
  'item/item.c',
  'player/abyss_core.c',
  'player/bomb.c',
  'player/charge_shot.c',
  'player/player.c',
  'player/recovery.c',
  'player/weapon.c',
  'render/hud.c',
  'render/japanese_text.c',
  'render/renderer.c',
  'render/screens.c',
  'stage/background.c',
  'stage/stage_controller.c',
  'system/audio.c',
  'system/debug.c',
  'system/input.c',
  'system/save.c',
];

const ENGINE_HEADER_FILES = [
  'bullet/enemy_bullet.h',
  'bullet/player_bullet.h',
  'collision/collision.h',
  'effect/effect.h',
  'enemy/boss.h',
  'enemy/enemy.h',
  'game/config.h',
  'game/game.h',
  'item/item.h',
  'player/abyss_core.h',
  'player/bomb.h',
  'player/charge_shot.h',
  'player/player.h',
  'player/recovery.h',
  'player/weapon.h',
  'render/hud.h',
  'render/japanese_text.h',
  'render/renderer.h',
  'render/screens.h',
  'stage/background.h',
  'stage/stage_controller.h',
  'stage/stage_definition.h',
  'system/audio.h',
  'system/debug.h',
  'system/input.h',
  'system/save.h',
];

function templateRoot() {
  return path.join(__dirname, 'template');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(source, destination) {
  ensureDir(path.dirname(destination));
  fs.copyFileSync(source, destination);
}

function copyTree(source, destination, filter = () => true) {
  if (!fs.existsSync(source)) return;
  fs.readdirSync(source, { withFileTypes: true }).forEach((entry) => {
    const sourcePath = path.join(source, entry.name);
    const relative = path.relative(source, sourcePath).replace(/\\/g, '/');
    if (!filter(entry, relative)) return;
    const destinationPath = path.join(destination, entry.name);
    if (entry.isDirectory()) copyTree(sourcePath, destinationPath, filter);
    else if (entry.isFile()) copyFile(sourcePath, destinationPath);
  });
}

function copyTreeMissing(source, destination) {
  if (!fs.existsSync(source)) return;
  fs.readdirSync(source, { withFileTypes: true }).forEach((entry) => {
    const sourcePath = path.join(source, entry.name);
    const destinationPath = path.join(destination, entry.name);
    if (entry.isDirectory()) {
      copyTreeMissing(sourcePath, destinationPath);
    } else if (entry.isFile() && !fs.existsSync(destinationPath)) {
      copyFile(sourcePath, destinationPath);
    }
  });
}

function generatedMainSource() {
  const source = fs.readFileSync(path.join(templateRoot(), 'src', 'main.c'), 'utf8').replace(/^\/\*[\s\S]*?\*\/\s*/m, '');
  return `/* Generated by horizontal-stg-builder v${manifest.version} */\n${source}`;
}

function syncEngine(projectDir, logger) {
  const root = templateRoot();
  ENGINE_SOURCE_FILES.forEach((relative) => copyFile(path.join(root, 'src', relative), path.join(projectDir, 'src', relative)));
  ENGINE_HEADER_FILES.forEach((relative) => copyFile(path.join(root, 'inc', relative), path.join(projectDir, 'inc', relative)));
  copyFile(path.join(root, 'src', 'boot', 'sega.s'), path.join(projectDir, 'src', 'boot', 'sega.s'));
  copyTreeMissing(path.join(root, 'res', 'gfx'), path.join(projectDir, 'res', 'gfx'));
  copyTreeMissing(path.join(root, 'res', 'font'), path.join(projectDir, 'res', 'font'));
  copyFile(path.join(root, 'src', 'main.c'), path.join(projectDir, 'src', 'main.c'));
  logger?.info?.('横スクロールSTGエンジンをプロジェクトへ同期しました');
}

function duplicateAssetDiagnostics(assets) {
  const names = new Map();
  const duplicates = [];
  (Array.isArray(assets) ? assets : []).forEach((asset) => {
    const name = String(asset?.name || '').trim();
    if (!name) return;
    if (names.has(name)) duplicates.push(`${name} (${names.get(name)} / ${asset.sourcePath || 'unknown'})`);
    else names.set(name, asset.sourcePath || 'unknown');
  });
  return duplicates;
}

function prepareProject(projectDir, assets, context = {}) {
  const duplicates = duplicateAssetDiagnostics(assets);
  if (duplicates.length) return { ok: false, error: `ResComp symbolが重複しています:\n${duplicates.join('\n')}` };
  syncEngine(projectDir, context.logger);
  fs.writeFileSync(path.join(projectDir, 'src', 'main.c'), generatedMainSource(), 'utf8');
  const exported = stgService.exportProject(projectDir);
  if (!exported.ok) {
    const details = (exported.errors || []).map((entry) => `${entry.path || '-'}: ${entry.message}`).join('\n');
    return { ok: false, error: `${exported.error || '横STGデータ生成に失敗しました'}${details ? `\n${details}` : ''}` };
  }
  (exported.warnings || []).forEach((warning) => context.logger?.warn?.(warning.message || String(warning)));
  const sourceFiles = [
    'src/main.c',
    ...ENGINE_SOURCE_FILES.map((relative) => `src/${relative}`),
    ...exported.source_files,
  ];
  return { ok: true, exported, sourceFiles: [...new Set(sourceFiles)].sort() };
}

function generateSource(assets = [], context = {}) {
  const projectDir = context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  try {
    const prepared = prepareProject(projectDir, context.assets || assets, context);
    if (!prepared.ok) return prepared;
    return { ok: true, sourceCode: generatedMainSource(), exported: prepared.exported };
  } catch (error) {
    return { ok: false, error: String(error?.message || error) };
  }
}

function onBuildStart(payload = {}, context = {}) {
  const projectDir = payload.projectDir || context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  try {
    const prepared = prepareProject(projectDir, context.assets || [], context);
    if (!prepared.ok) return prepared;
    context.logger?.info?.(`横STGデータを生成しました (${prepared.exported.report.counts.stages} stage / ${prepared.exported.report.counts.events} event)`);
    return {
      ok: true,
      makeVariables: {
        SRC_C: prepared.sourceFiles.join(' '),
      },
    };
  } catch (error) {
    return { ok: false, error: String(error?.message || error) };
  }
}

function onBuildLog() {
  return { ok: true };
}

function onBuildEnd(payload = {}, context = {}) {
  try {
    const romPath = payload.romPath || payload.outputPath;
    if (romPath && fs.existsSync(romPath)) {
      const bytes = fs.statSync(romPath).size;
      const snapshot = stgService.readSnapshot(payload.projectDir || context.projectDir);
      const hardLimit = snapshot.project.rom.hard_limit_bytes;
      const target = snapshot.project.rom.target_bytes;
      if (bytes > hardLimit) return { ok: false, error: `ROMがhard limitを超えています: ${bytes} / ${hardLimit} bytes` };
      const message = `横STG ROM: ${bytes} bytes (target ${target}, hard ${hardLimit})`;
      if (bytes > target) context.logger?.warn?.(message);
      else context.logger?.info?.(message);
    }
    return { ok: true };
  } catch (error) {
    return { ok: false, error: String(error?.message || error) };
  }
}

function onBuildError(payload = {}, context = {}) {
  context.logger?.error?.(`横STGビルドエラー: ${payload.error || 'unknown error'}`);
  return { ok: true };
}

module.exports = {
  manifest,
  ENGINE_SOURCE_FILES,
  ENGINE_HEADER_FILES,
  generateSource,
  onBuildStart,
  onBuildLog,
  onBuildEnd,
  onBuildError,
};
