#ifndef GERONEKO_CONFIG_H
#define GERONEKO_CONFIG_H

#include "generated/game_config.h"

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 224

#define HUD_ROWS 2
#define GAMEPLAY_TOP_PX (HUD_ROWS * 8)

#define FIXED_SHIFT 8
#define FIXED_ONE (1 << FIXED_SHIFT)

#define MAX_ENEMIES STG_MAX_ENEMIES
#define MAX_PLAYER_BULLETS STG_MAX_PLAYER_BULLETS
#define MAX_ENEMY_BULLETS STG_MAX_ENEMY_BULLETS
#define MAX_CHARGE_SHOTS STG_MAX_CHARGE_SHOTS
#define MAX_ITEMS STG_MAX_ITEMS
#define MAX_EFFECTS STG_MAX_EFFECTS


#define PLAYER_INITIAL_LIVES STG_START_LIVES
#define PLAYER_HIT_FRAMES 36
#define PLAYER_INVINCIBLE_FRAMES STG_RESPAWN_INVINCIBLE_FRAMES

#define WEAPON_LEVEL_MIN 1
#define WEAPON_LEVEL_MAX 3

#define SAME_ATTRIBUTE_SCORE_BONUS STG_SAME_ATTRIBUTE_SCORE
#define POWER_MAX_SCORE_BONUS STG_MAX_POWER_SCORE

#define ITEM_POP_FRAMES 24
#define ITEM_POP_VY256 (-1 * FIXED_ONE)
#define ITEM_DRIFT_VX256 (-1 * FIXED_ONE)

#define CHARGE_MID_FRAMES STG_CHARGE_MID_FRAMES
#define CHARGE_MAX_FRAMES STG_CHARGE_MAX_FRAMES

#define CHARGE_MID_DAMAGE 4
#define CHARGE_MAX_DAMAGE 8
#define CHARGE_SPEED256 (5 * FIXED_ONE)

#define CORE_LAUNCH_SPEED256 (4 * FIXED_ONE)
#define CORE_RETURN_SPEED256 (4 * FIXED_ONE)
#define CORE_FOLLOW_SPEED256 (2 * FIXED_ONE)
#define CORE_DETACHED_OFFSET_X 72
#define CORE_OVERLAP_HIT_INTERVAL 12
#define CORE_LAUNCH_DAMAGE 2

#define SPEED_LEVEL_MIN 1
#define SPEED_LEVEL_MAX 3
#define SPEED_MAX_SCORE_BONUS STG_MAX_SPEED_SCORE

#define BOMB_INITIAL_STOCK STG_START_BOMBS
#define BOMB_MAX_STOCK STG_MAX_BOMBS
#define BOMB_MAX_SCORE_BONUS STG_MAX_BOMB_SCORE
#define CORE_DUPLICATE_SCORE_BONUS STG_DUPLICATE_CORE_SCORE

#define BOMB_ACTIVE_FRAMES STG_BOMB_ACTIVE_FRAMES

#define PLAYER_SPEED_LV1_256 (2 * FIXED_ONE)
#define PLAYER_SPEED_LV2_256 (3 * FIXED_ONE)
#define PLAYER_SPEED_LV3_256 (4 * FIXED_ONE)

#define BOMB_SMALL_ENEMY_DAMAGE 255

#define RECOVERY_FIRST_DELAY 90
#define RECOVERY_SECOND_DELAY 240
#define RECOVERY_CARRIER_VX256 (-2 * FIXED_ONE)
#define CORE_OVERLAP_DAMAGE 1
#define ENEMY_BULLET_SPEED256 (-2 * FIXED_ONE)

#define PLAYER_START_X 64
#define PLAYER_START_Y 112
#define PLAYER_SPEED256 (2 * FIXED_ONE)

#define PLAYER_BULLET_SPEED256 (4 * FIXED_ONE)

#define INVALID_RENDER_HANDLE 0xFF

#define MAX_BOSS_PARTS 3
#define MAX_BOSS_RENDER_PARTS 3

#endif
