# Generated by md-novel-builder
TILESET novel_font_subset "novel/font/generated.png" NONE NONE
IMAGE nov_bg_bg_sample_7d16a41f "novel/backgrounds/nov_bg_bg_sample_7d16a41f.png" NONE ALL 0
SPRITE nov_spr_sp_hero_b74c1708 "novel/sprites/nov_spr_sp_hero_b74c1708.png" 4 8 NONE [[12]] NONE BALANCED FAST FALSE
XGM2 nov_bgm_sample_bgm_ch0_2f696355 "novel/music/nov_bgm_sample_bgm_ch0_2f696355.vgm"
WAV nov_sfx_sample_sfx_ch0_aa319e7c "novel/sfx/nov_sfx_sample_sfx_ch0_aa319e7c.wav" XGM2 6650 FALSE
